### ISSUE TITLE
c++11 range for and non copyable.

### ISSUE THREAD

**Issue by sagaceilo** [greg7mdp/sparsepp#24] opened 2017-01-12 07:59 UTC
Hello !

I've noticed some problems when adopting Your sparsepp. Mostly they occur when dealing with objects that are non copyable (they copy constructor and assign operator are deleted).

Lets say we have:
```
for( auto& it : m_values )
{
	it.second.RestoreDefault();
}
```

There is simple loop through references to all items in hash map. sparsepp wants to do this:

```
// sparsepp (2615)
    void _set_val(mutable_value_type *p, const_reference val)
    {
        *p = spp_const_mutable_ref(val);
    }
```

So it unrolls to simple assign operator `*p = (*(reinterpret_cast<const_mutable_pointer>(&(x))))`
It would be cool to support such objects, especially that Your hasmap should be easy plug&play replacement for std one.

Any way, lib is great and looking to hearing from You ;)

**Comment by greg7mdp** [comment] 2017-01-12 14:02
@sagaceilo, thank you very much for the report. I'll look into it asap, maybe over the week-end. Would you have a small sample that reproduces the issue? Also what happens, is it a build issue? Also are you using the latest version, I added support for non-copyable objects a couple weeks ago.

**Comment by sagaceilo** [comment] 2017-01-13 07:58
Hey!
Here is example:

```c++
#if 1
#	define SPP_NO_EXCEPTIONS
#	define SPP_NO_RTTI
#	include <sparsepp/sparsepp.h>

	template <typename HashType, typename ObjType>
	using THashMap = spp::sparse_hash_map<HashType, ObjType>;
#endif

#if 0
#	include <sparsehash/sparse_hash_map>

	template <typename HashType, typename ObjType>
	using THashMap = ::google::sparse_hash_map<HashType, ObjType>;
#endif

#if 0
#	include <unordered_map>

	template <typename HashType, typename ObjType>
	using THashMap = std::unordered_map<HashType, ObjType>;
#endif

class CNonCopyable
{
public:
	CNonCopyable( CNonCopyable const & ) = delete;
	const CNonCopyable& operator=( CNonCopyable const & ) = delete;
	CNonCopyable() = default;
};


struct Probe : CNonCopyable
{
	Probe() {}
	Probe( Probe && other ) {}
	void operator=( Probe && other )	{}
};
```
```c++
void main() {
THashMap<uint64_t,Probe> probes;

probes.insert( { 0, Probe() } );

for( auto& it : probes ) {}
}
```

I've tried cut as many non revelant code I've could. Hope that You will find this helpful. It runs and compiles using std::unordered_map.

**Comment by greg7mdp** [comment] 2017-01-16 22:05
Thank you @sagaceilo , your sample program is very useful. Somehow, using my versions of gcc and clang (4.8.3 and 3.8 on linux), your sample as-is does not compile even when using std::unordered_map, because of the insert with the initializer_list.

However, it does build with a simple change, replacing:
`probes.insert( { 0, Probe() } );`
with:
`probes.insert( THashMap<uint64_t, Probe>::value_type(27, Probe()) );`

I did update sparsepp a few minutes ago, and now your updated sample builds as well with sparsepp. Please let me know if this version is OK with you.

**Comment by sagaceilo** [comment] 2017-01-17 11:31
Now it works like a charm :) Thank you ;)

**Comment by greg7mdp** [comment] 2017-01-17 13:31
Great, thanks for letting me know, closing the issue.

**Closed by greg7mdp** 2017-01-17 13:31 UTC
